
# spring boot yml configuration
server:
  port: 9090
  context-path: /v1

datasource:
  first:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.101:3306/udpo?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 10
      max-wait: 10000
      min-evictable-idle-time-millis: 60000
      min-idle: 3
      initial-size: 5
      validation-query: select 1 limit 1
      validation-interval: 30000
      validation-query-timeout: 20
      test-on-borrow: true
      test-on-connect: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 5000
      remove-abandoned: true
      remove-abandoned-timeout: 300
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer
      rollback-on-return: true
      commit-on-return: false
      alternate-username-allowed: false
      jmx-enabled: false
  second:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.101:3306/udpo_b?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 10
      max-wait: 10000
      min-evictable-idle-time-millis: 60000
      min-idle: 3
      initial-size: 5
      validation-query: select 1 limit 1
      validation-interval: 30000
      validation-query-timeout: 20
      test-on-borrow: true
      test-on-connect: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 5000
      remove-abandoned: true
      remove-abandoned-timeout: 300
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer
      rollback-on-return: true
      commit-on-return: false
      alternate-username-allowed: false
      jmx-enabled: false
spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.101:3306/udpo?characterEncoding=utf8&useSSL=true
#    driver-class-name: com.mysql.jdbc.Driver
#    tomcat:
#      max-active: 20
#      max-idle: 10
#      max-wait: 10000
#      min-evictable-idle-time-millis: 60000
#      min-idle: 3
#      initial-size: 5
#      validation-query: select 1 limit 1
#      validation-interval: 30000
#      validation-query-timeout: 20
#      test-on-borrow: true
#      test-on-connect: true
#      test-on-return: true
#      test-while-idle: true
#      time-between-eviction-runs-millis: 5000
#      remove-abandoned: true
#      remove-abandoned-timeout: 300
#      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer
#      rollback-on-return: true
#      commit-on-return: false
#      alternate-username-allowed: false
#      jmx-enabled: false
  jpa:
    show-sql: true
    database: mysql
  mvc:
    throw-exception-if-no-handler-found: true
    date-format: yyyy-MM-dd HH:mm:ss
    static-path-pattern: /**
security:
  basic:
    enabled: false
# Mybatis configuration
mybatis:
#  type-aliases-package: zxw.app.udpo.core.entity
#  type-handlers-package: zxw.app.udpo.core.entity
  configuration:
    default-fetch-size: 100
#    该配置影响的所有映射器中配置的缓存的全局开关。	true | false	true
    cache-enabled: true
#    延迟加载的全局开关。当开启时，所有关联对象都会延迟加载。 特定关联关系中可通过设置fetchType属性来覆盖该项的开关状态。	true | false	false
    lazy-loading-enabled: true
#    当开启时，任何方法的调用都会加载该对象的所有属性。否则，每个属性会按需加载（参考lazyLoadTriggerMethods).	true | false	false (true in ≤3.4.1)
    aggressive-lazy-loading: false
#    是否允许单一语句返回多结果集（需要兼容驱动）。	true | false	true
    multiple-result-sets-enabled: true
#    使用列标签代替列名。不同的驱动在这方面会有不同的表现， 具体可参考相关驱动文档或通过测试这两种不同的模式来观察所用驱动的结果。	true | false	true
    use-column-label: true
#    允许 JDBC 支持自动生成主键，需要驱动兼容。 如果设置为 true 则这个设置强制使用自动生成主键，尽管一些驱动不能兼容但仍可正常工作（比如 Derby）。	true | false	False
    use-generated-keys: true
#    指定 MyBatis 应如何自动映射列到字段或属性。 NONE 表示取消自动映射；PARTIAL 只会自动映射没有定义嵌套结果集映射的结果集。 FULL 会自动映射任意复杂的结果集（无论是否嵌套）。	NONE, PARTIAL, FULL	PARTIAL
    auto-mapping-behavior: PARTIAL
#    指定发现自动映射目标未知列（或者未知属性类型）的行为。
#    NONE: 不做任何反应
#    WARNING: 输出提醒日志 ('org.apache.ibatis.session.AutoMappingUnknownColumnBehavior' 的日志等级必须设置为 WARN)
#    FAILING: 映射失败 (抛出 SqlSessionException)
#    NONE, WARNING, FAILING	NONE
    auto-mapping-unknown-column-behavior: NONE
#    配置默认的执行器。SIMPLE 就是普通的执行器；REUSE 执行器会重用预处理语句（prepared statements）； BATCH 执行器将重用语句并执行批量更新。	SIMPLE REUSE BATCH	SIMPLE
    default-executor-type: reuse
#    允许在嵌套语句中使用分页（RowBounds）。如果允许使用则设置为false。	true | false	False
    safe-row-bounds-enabled: false
#    允许在嵌套语句中使用分页（ResultHandler）。如果允许使用则设置为false。	true | false	True
    safe-result-handler-enabled: true
#    是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射。	true | false	False
    map-underscore-to-camel-case: true
#    MyBatis 利用本地缓存机制（Local Cache）防止循环引用（circular references）和加速重复嵌套查询。 默认值为 SESSION，这种情况下会缓存一个会话中执行的所有查询。 若设置值为 STATEMENT，本地会话仅用在语句执行上，对相同 SqlSession 的不同调用将不会共享数据。	SESSION | STATEMENT	SESSION
    local-cache-scope: session
#    当没有为参数提供特定的 JDBC 类型时，为空值指定 JDBC 类型。 某些驱动需要指定列的 JDBC 类型，多数情况直接用一般类型即可，比如 NULL、VARCHAR 或 OTHER。	JdbcType enumeration. Most common are: NULL, VARCHAR and OTHER	OTHER
    jdbc-type-for-null: OTHER
#    指定动态 SQL 生成的默认语言。	A type alias or fully qualified class name.	org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
    default-scripting-language: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
#    Specifies the TypeHandler used by default for Enum. (Since: 3.4.5)	A type alias or fully qualified class name.	org.apache.ibatis.type.EnumTypeHandler
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
#    指定当结果集中值为 null 的时候是否调用映射对象的 setter（map 对象时为 put）方法，这对于有 Map.keySet() 依赖或 null 值初始化的时候是有用的。注意基本类型（int、boolean等）是不能设置成 null 的。	true | false	false
    call-setters-on-nulls: false
#    当返回行的所有列都是空时，MyBatis默认返回null。 当开启这个设置时，MyBatis会返回一个空实例。 请注意，它也适用于嵌套的结果集 (i.e. collectioin and association)。（从3.4.2开始）	true | false	false
    return-instance-for-empty-row: false
#    指定 MyBatis 增加到日志名称的前缀。	Any String	Not set
    log-prefix: MyBatis
#    指定 Mybatis 创建具有延迟加载能力的对象所用到的代理工具。	CGLIB | JAVASSIST	JAVASSIST (MyBatis 3.3 or above)
#    proxy-factory: JAVASSIST
#    映射器接口类和映射xml在统一路径下,可以不写
#  mapper-locations: zxw.app.udpo.core.mapper


