# spring boot yml configuration

server:
  port: 9090
  context-path: /v1
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.101:3306/udpo?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 10
      max-wait: 10000
      min-evictable-idle-time-millis: 60000
      min-idle: 3
      initial-size: 5
      validation-query: select 1 limit 1
      validation-interval: 30000
      validation-query-timeout: 20
      test-on-borrow: true
      test-on-connect: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 5000
      remove-abandoned: true
      remove-abandoned-timeout: 300
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer
      rollback-on-return: true
      commit-on-return: false
      alternate-username-allowed: false
      jmx-enabled: false
  jpa:
    show-sql: true
    database: mysql
  mvc:
    throw-exception-if-no-handler-found: true
    date-format: yyyy-MM-dd HH:mm:ss
    static-path-pattern: /**
security:
  basic:
    enabled: false


